config/routes.rb
Rails.application.routes.draw do
  resources :groups do 
    post 'invitations', to: 'invitations#create'
    patch 'invitations', to: 'invitations#update'
    get 'invitations', to: 'invitations#show'
    post 'join', to: 'groups#join'
    post 'message', to: 'messages#create'
    resources :games do
      resources :game_responds
    end
    patch 'dm', to: 'groups#assign_dm'
  end

  resources :messages do
    resources :comments
  end

  devise_for :users 
  resource :users
  match '/users/:id', to: 'users#show', via: 'get'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :group
  has_one :message
  has_many :game_responds
end

app/models/game_respond.rb
class GameRespond < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :messages, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :games, dependent: :destroy
  has_one_attached :image
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
  
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :sender, class_name: 'User'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :comments, dependent: :destroy
  belongs_to :game, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :group_users 
  has_many :groups, through: :group_users
  has_many :invitations
  has_many :game_responds

  has_one_attached :avatar

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email address latitude longitude rating dm terms alignment username bio avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[email location dm alignment username bio avatar])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @group = Group.find(params[:group_id])
    @message = Message.find(params[:message_id])
    @comment = @message.comments.create(comment_params)
    redirect_to group_path(@group)
  end

  def destroy
    @message = Message.find(params[:message_id])
    @comment = @message.comments.find(params[:id])
    @comment.destroy
    redirect_to groups_path
  end 

  private 

  def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def create
    @group = Group.find(params[:group_id])
    @game = Game.create(game_params)
    @message = Message.create(message_params)
    @message.save!
    redirect_to group_path(@group)
  end

  def update
    game = Game.find(params[:id])
    game.update_column(:complete, true)
    players = GameRespond.where(game_id: game.id)
    players.each do |player| 
      player.user.rating += 13
      player.user.save!
    end
    redirect_to group_path(params[:group_id])
  end

  private 

  def message_params
    params.permit(:group_id).merge(game_id: @game.id, user_id: current_user.id)
  end

  def game_params
    params.permit(:date, :time, :name, :location).merge(group_id: @group.id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @groups = Group.all
  end

  def show
    group_id = params[:id]
    @user = GroupUser.find_by(group_id: group_id, user_id: current_user.id)
    @messages = Message.where(group_id: group_id)
    @requests = Invitation.where(group_id: group_id, confirmed: false)
    @users = GroupUser.where(group_id: group_id)
    @games = Game.where(group_id: group_id)
  end

  def new
    @group = Group.new
  end

  def assign_dm 
    dm = GroupUser.find_by(group_id: params[:group_id], user_id: params[:user_id])
    dm.update_column(:dm, true)
    redirect_to group_path(params[:group_id])
  end

  def edit
    group = Group.where(id: @group.id)
  end

  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        @user_group = GroupUser.create(group_user_params)
        format.html { redirect_to @group, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :party_size, :information, :game_edition, :campaign_type, :image, :party_level)
    end

    def group_user_params
      params.require(:group).permit(:character_name, :character_race, :character_class).merge(group_id: @group.id, user_id: current_user.id, admin: true)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index 
      @user = User.find(current_user.id)
      @users = User.all
      @groups = Group.all
      @group_users = GroupUser.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @group = Group.find(params[:group_id])
    @message = Message.create(message_params)
    @message.save!
    redirect_to group_path(@group)
  end

  private 

  def message_params 
    params.permit(:content, :group_id).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @users = User.all
    @groups = Group.all
    @group_users = GroupUser.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_for(user)
    if user.avatar.attached?
      user.avatar
    else
      'default_avatar.jpg'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/game_responds_helper.rb
module GameRespondsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/comments/_comments.html.erb
<%= comment.name %>
<%= comment.body %>
<%= time_ago_in_words(comment.created_at) %>

app/views/comments/_form.html.erb
<%= form_for([@message, @message.comments.build]) do |f| %>

  <p><%= f.label :name %></p>
  <p>
    <%= f.label :body %><br/>
    <%= f.test_area :body, required: true %>
  </p>
  <br>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/groups/_admin_functions.html.erb
<div class="admin-function">
  <% if !@user.nil? && @user.admin? %>
  <% @requests.each do |request| %>
  <div class="user-request">
    <h1><%= request.sender.username %></h1>
    <div class="request-details">
      <p>Character Name: <%= request.character_name %>, Race: <%= request.character_race %>, Class: <%= request.character_class %> requests to join your party</p>
      <%= link_to 'Accept', group_invitations_path(user_id: request.sender.id, group_id: @group.id), method: 'patch', class: 'accept' %>
    </div>
    
    </div>
  <% end %>
<% end %>
</div>

app/views/groups/_chat.html.erb
<div class="chat-box">
  <div class="new-message">
    <% if !@user.nil? %>
      <%= form_with url: group_message_path(@group), method: 'post' do |f| %>
        <%= f.text_area :content, required: true %>
        <button class="message_btn" type="submit" name="commit" data-disable-with="Send"><i class="far fa-comment-dots"></i></button>
      <% end %>
    <% end %>
  </div>

  <% if !@user.nil? %>
    <div class="chat-window">

      <% @messages.each do |message| %>
                          
        <% if !message.game_id.nil? %>
          Game scheduled: <%= message.game.name %> at <%= message.game.location %> for <%= message.game.date.strftime("%d/%m/%Y") %> at <%= message.game.time.strftime("%k:%M") %>
        <% else %>

          <% if message.user.username == current_user.username %>                   
            <div class="message-current-user">
          <% else %>
            <div class="message">
          <% end %>
              <div class="message-title">
                <h3><%= message.user.username %> Posted</h3>
              </div>
              <div class="message-content">
                <%= message.content %>
                <div class="comments">
                  <% message.comments.each do |comment| %>
                    <div class="comment-title">
                      <p><%= comment.name %></p>
                    </div>
                    <div class="comment-content">
                      <p><%= comment.body %></p>
                    </div>
                  <% end %>
                </div>
              </div>

              <%= form_with url: message_comments_path(message_id: message.id, group_id: @group.id), method: :post do |f| %>
                <p>
                  <input type="hidden" name="comment[name]" id="comment_name" value="<%= current_user.username %>">
                </p>
                <div class="comment-textarea">
                  <textarea name="comment[body]" id="comment_body" placeholder="Comment here..." required></textarea>
                  <button class="comment_btn" type="submit" name="commit"><i class="far fa-comment"></i></button>
                </div>
              
            </div>
          <% end %>
        <% end %>
        
      <% end %>
    </div>
  <% end %>
</div>

app/views/groups/_form.html.erb
<div class="left-content-container">
  <%= image_tag("dice.png", :alt => "Game Dice Logo", :class => "logo") %>
  <h1 class="land-page-title">Tavern Keepers</h1>
  <h3 class="land-page-subtitle">Create Your Tavern</h3>
</div>
<div class="right-content-container">
  <%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="reg-box">
      <div class="address">
        <%= form.label :name %>
        <%= form.text_field :name, required: true %>
      </div>
    </div>
    <br>
    <div class="reg-box">
      <div class="bio">
        <%= form.label :information %>
        <%= form.text_area :information, required: true %>
      </div>
    </div>
    <br>
    <div class="reg-box">
      <div class="avatar"> 
        <%= form.label "Image" %>
        <%= form.file_field :image %><br>
      </div>
      <div class="alignment">
        <%= form.label :party_size %>
        <%= form.select :party_size, [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] %>
      </div>
      <div class="alignment">
        <%= form.label :party_level %>
        <%= form.select :party_level, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] %>
      </div>
    </div>
    <br>
    <div class="reg-box">
      <div class="avatar">
        <%= form.label :game_edition %>
        <%= form.select :game_edition, ['D&D', 'AD&D', '2e', '3e', '3.5', '4e', '5e'] %>
      </div>
      <div class="avatar">
        <%= form.label :campaign_type %>
        <%= form.select :campaign_type, ['Homebrew', 'Module'] %>
      </div>
    </div>
  <br>
  <div>
    <h2>Your Character:</h2>
  </div>
  <br>
  <div class="reg-box">
    <div class="password">
      <%= form.label :character_name %>
      <%= form.text_field :character_name, required: true %>
    </div>
    <div class="password">
      <%= form.label :character_race %>
      <%= form.text_field :character_race, required: true %>
    </div>
  </div>
  <br>
  <div class="reg-box">
    <div class="alignment">
      <%= form.label :character_class %>
      <%= form.select :character_class, ['Barbarian', 'Bard', 'Cleric', 'Druid', 'Fighter', 'Monk', 'Paladin', 'Ranger', 'Rogue', 'Sorcerer', 'Warlock', 'Wizard'] %>
    </div>
  </div>
  <br>
  <div class="reg-btn">
    <div class="sign-up-btn">
      <%= form.submit %>
    </div>
  </div>
<% end %>
</div>

app/views/groups/_group_info.html.erb
<div class="group-info">
  <div class="group-title">
    <% if @group.image.attached? %>
    <%= image_tag @group.image %>
    <% else %>
    <p>No image</p>
    <% end %>
    <div class="group-details">
      <h1><%= @group.name %></h1>
      <p>
        <%= @group.information %>
      </p>
      <p>Battling since <%= time_ago_in_words(@group.created_at) %> ago</p>
      <p>
        <% if @group.group_users.length == 1 %>
        <%= @group.group_users.length %> Ally of <%= @group.party_size %>
        <% else %>
        <%= @group.group_users.length %> Allies of <%= @group.party_size %>
        <% end %>
      </p>
      <p>
        <% if (@group.party_size - @group.group_users.length) == 1 %>
        <%= @group.party_size - @group.group_users.length %> Seat available, if you are worthy.
        <% else %>
        <%= @group.party_size - @group.group_users.length %> Seats available, if you are worthy.
        <% end %>
      </p>
      <p>Game Edition: <%= @group.game_edition %></p>
      <% if !@user.nil? && @user.admin? %>
      <%= link_to 'Delete Group', @group, method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-group' %>
      <% end %>
    </div>
  </div>
  
  
    <% if !@user.nil? && (@user.admin? || @user.dm?) %>
    <div class="new-group-btn">
      <a class="edit-btn" data-method="get" href="/groups/<%= @group.id %>/edit"><i class="fas fa-edit"></i></a>
    </div>
    <% end %>
</div>

app/views/groups/_requests.html.erb
<% if @users.length < @group.party_size %>
  <% if @user.nil? && !Invitation.where(group_id: @group.id, sender_id: current_user.id).exists? %>
    <%= button_to "Request", group_invitations_path(@group), method: 'get' %> 
  <% end %> 
<% end %>

app/views/groups/_schedule.html.erb
<div class="game-schedule">
  <div class="schedular">
    <% if !@user.nil? && @user.admin? %>
    <%= form_with url: group_games_path(@group), method: 'post' do |f| %>
    <h3>Schedule a Battle</h3>
    <!-- <%= f.label :name %> -->
    <%= f.text_field :name, required: true, placeholder: 'Battle Name', id: 'name' %>

    <div class="date-time">
      <!-- <%= f.label :date %> -->
      <%= f.date_field :date, required: true, id: 'date' %>
      <!-- <%= f.label :time %> -->
      <%= f.time_field :time, required: true, id: 'time' %>
    </div>
    <!-- <%= f.label :location %><br> -->
    <%= f.text_field :location, required: true, placeholder: 'Location' %>

    <%= f.submit "Schedule game" %>
    <% end %>
    <% end %>
  </div>
  <div class="games">
    <h3>Scheduled Games</h3>
    <% @games.each do |game| %>
    <div class="game">
      <p><%= game.name %></p>
      <p>Date: <%= game.date %></p>
      <p>Time: <%= game.time.strftime("%k:%M") %></p>
      <p>Location: <%= game.location %></p>
      <% check_user = game.game_responds.find { |player| player.user.id == current_user.id } %>
      <% if check_user %>
      <p>
        <!-- <%= link_to 'Going', group_game_game_respond_path(game_id: game.id, group_id: @group.id), method: :delete %>Going -->
        <a class="not-att" href="/groups/<%= @group.id %>/games/<%= game.id %>/game_responds/<%= @user.id %>" rel="nofollow" data-method="delete"><i class="far fa-thumbs-down"></i> Not Attending</a>
      </p>
      <% else %>
      <p>
        <!-- <%= link_to 'Going', group_game_game_responds_path(@group.id, game.id), method: :post %>  -->
        <a class="att" href="/groups/<%= @group.id %>/games/<%= game.id %>/game_responds" rel="nofollow" data-method="post"><i class="far fa-thumbs-up"></i> Attending</a>
        
      </p>
      <% end %>
      <p>
        <%= game.game_responds.count %> Attending
      </p>
      <% if !game.complete? && @user.admin? %>
      <p><%= link_to 'End Session', group_game_path(@group.id, game.id), method: :patch %></p>
      <% end %>
      <h3>Attending</h3>
      <div class="attending">
        <% game.game_responds.each do |response| %>
        <p>&nbsp;<a href="/users/<%= response.user_id %>"><%= response.user.username %> </a><span>-</span></p>

        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/groups/_user_list.html.erb
<div class="admin-function">
  <% if GroupUser.where(group_id: @group.id, admin: true).exists? %>

  <% end %>
  <div class="user-request">
    <h1>Admin:</h1>
    <div class="player-details">
      <% @users.each do |group_user| %>
      <% if group_user.admin? %>
      <%= group_user.user.username %> - <%= group_user.character_name %>, <%= group_user.character_race %>
      <%= group_user.character_class %>
      <% end %>
      <% end %>
    </div>
    <% if GroupUser.where(group_id: @group.id, admin: false, dm: true).exists? %>
      <h1>DM:</h1>
      <% end %>
    <div class="player-details">
      <% @users.each do |group_user| %>
      <% if !group_user.admin? && group_user.dm? %>
      <p>
        <%= group_user.user.username %> - <%= group_user.character_name %>, <%= group_user.character_race %>
      <%= group_user.character_class %>
      </p>
      <% end %>
      <% end %>
    </div>
    <% if GroupUser.where(group_id: @group.id, admin: false, dm: false).exists? %>
      <h1>Players:</h1>
    <% end %>
    <% @users.each do |group_user| %>
    <div class="player-details">
      <p>
      
        <% if !group_user.admin? && !group_user.dm? %>
          <%= group_user.user.username %> - <%= group_user.character_name %>, <%= group_user.character_race %>
          <%= group_user.character_class %>
      </p>
          <% if !@user.nil? && @user.admin? %>
          <%= link_to 'Assign DM', group_dm_path(group_id: @group, user_id: group_user.user.id), method: 'patch', class: 'accept' %>
          <% end %>
      <% end %>
      
    </div>
    <% end %>
  </div>
</div>

app/views/groups/edit.html.erb
<div class="reg-land-page">
  <div class="center-content-container">
    <div class="left-content-container">
      <%= image_tag("dice.png", :alt => "Game Dice Logo", :class => "logo") %>
      <h1 class="land-page-title">Tavern Keepers</h1>
      <h3 class="land-page-subtitle">Update Your Tavern</h3>
    </div>
    <div class="right-content-container">
      <%= form_with model: @group, url: group_path(@group), method: 'patch' do |form| %>
      <div class="reg-box">
        <div class="address">
          <%= form.label :name %>
          <%= form.text_field :name, required: true %>
        </div>
      </div>
      <br>
      <div class="reg-box">
        <div class="bio">
          <%= form.label :information %>
          <%= form.text_area :information, required: true %>
        </div>
      </div>
      <br>
      <div class="reg-box">
        <div class="avatar">
          <%= form.label "Image" %>
          <%= form.file_field :image %><br>
        </div>
        <div class="alignment">
          <%= form.label :party_size %>
          <%= form.select :party_size, [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] %>
        </div>
        <div class="alignment">
          <%= form.label :party_level %>
          <%= form.select :party_level, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] %>
        </div>
      </div>
      <br>
      <div class="reg-box">
        <div class="avatar">
          <%= form.label :game_edition %>
          <%= form.select :game_edition, ['D&D', 'AD&D', '2e', '3e', '3.5', '4e', '5e'] %>
        </div>
        <div class="avatar">
          <%= form.label :campaign_type %>
          <%= form.select :campaign_type, ['Homebrew', 'Module'] %>
        </div>
      </div>
      <br>
      <div>
        <h2>Your Character:</h2>
      </div>
      <br>
      <div class="reg-btn">
        <div class="sign-up-btn">
          <%= form.submit %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="taverns-land-page">
  <div class="page-banner">
    <h1 class="banner-heading">Tavern Keepers</h1>
  </div>
  <div class="taverns-center-container">
    <div class="taverns-title">
      <h1>Taverns</h1>
    </div>

    <div class="taverns">
      <% @groups.each do |group| %>
        <div class="tavern">
          <div class="tavern-image">
            <% if !group.image.attached? %>
              <p>No Image</p>
            <% else %>
              <%= image_tag group.image %>
            <% end %>
          </div>
          <div class="tavern-details">
            <h1><%= link_to group.name, group %></h1>
            <p><%= group.information %></p>
            <p>Battling since <%= time_ago_in_words(group.created_at) %> ago</p>
            <p>
              <% if group.group_users.length == 1 %>
              <%= group.group_users.length %> Ally of <%= group.party_size %>
              <% else %>
              <%= group.group_users.length %> Allies of <%= group.party_size %>
              <% end %>
            </p>
              <p>
                <% if (group.party_size - group.group_users.length) == 1 %>
                <%= group.party_size - group.group_users.length %> Seat available, if you are worthy.
                <% else %>
                <%= group.party_size - group.group_users.length %> Seats available, if you are worthy.
                <% end %>
              </p>
          </div>
          
        </div>
      <% end %>
    </div>

    <div class="new-group-btn">
      <!-- <%= link_to 'New Group', new_group_path %> -->
      <a class="link_btn" href="/groups/new"><i class="fas fa-users"></i></a>
    </div>
    
  </div>
  
</div>

app/views/groups/new.html.erb
<div class="reg-land-page">
  <div class="center-content-container">

    <%= render 'form', group: @group %>

    
  </div>
  <%= link_to 'Cancel', groups_path %>
</div>

app/views/groups/show.html.erb
<div class="taverns-land-page">

  <div class="page-banner">
    <h1 class="banner-heading">Tavern Keepers</h1>
  </div>
  <div class="taverns-center-container">
    <%= render 'group_info' %>

    <div class="user-game-info">
      <%= render 'user_list' %>
      <%= render 'schedule' %>
    </div>
    

    <%= link_to 'Back', groups_path %>

    <%= render 'admin_functions' %>

    <%= render 'requests' %>

    <%= render 'chat' %>

  </div>
</div>